### ISSUE TITLE
revert function

### ISSUE THREAD

**Issue by RichardSieg** [sebasguts/PyNormaliz#10]
revert all computation goals

**Comment by RichardSieg** [comment]
A revert function actually does not make much sense. The only thing needed is the HSOP flag: If set true, we always should have the HSOP representation, if set false explicitely, always the standard. I will include that in the HilbertSeries function.

**Comment by RichardSieg** [comment]
The problem is, that once the IsComputed(HSOP) flag is set, it stays like this. So also if we type C.HilbertSeries(HSOP=False) and the HSOP form has been computed before, it will print out the HSOP form. 

We could just leave it like this. Otherwise we probably would need a setCompute function in the module as well, which then could set  this flag false.

**Comment by sebasguts** [comment]
Does `HSOP` do anything else except for `HilbertSeries`? Otherwise, we could actually pass this as an argument. I think there is no way to reset this in libNormaliz itself, which makes sense.

**Comment by RichardSieg** [comment]
It only creates a new form for the HilbertSeries. We could pass this as an argument. The old form is still there (just the usual getNum, getDenom)

**Comment by sebasguts** [comment]
Almost did it. Only problem left: If the Hilbert series is computed once with `HSOP` is set to false, the `HSOP` parts of the Hilbert series are not computed correctly, i.e.:
```
>>> C = Cone( cone=[[1,2],[2,1]], grading=[1,1] )
>>> C.HilbertSeries(HSOP=False)
[[1, -1, 1], [1, 3], 0]
>>> C.HilbertSeries(HSOP=True)
[[], [], 0]
````
The other way around seems to work.
```
>>> C = Cone( cone=[[1,2],[2,1]], grading=[1,1] )
>>> C.HilbertSeries(HSOP=True)
[[1, 0, 1, 0, 1], [3, 3], 0]
>>> C.HilbertSeries(HSOP=False)
[[1, -1, 1], [1, 3], 0]
```
Any ideas? Is this intentional or a bug?

**Comment by sebasguts** [comment]
In the `HilbertSeries` branch you can now find the code I used.

**Comment by RichardSieg** [comment]
I wrote a HOTFIX that recomputes the HilbertSeries in this case.

We will rewrite the structure in Normaliz next week to avoid this.

Note that this needs a revert ConeProperty function in cone.cpp:

```
template<typename Integer>
void Cone<Integer>::resetComputed(ConeProperty::Enum prop){
    is_Computed.reset(prop);
}
```

(since is_Computed is private)

**Comment by sebasguts** [comment]
So you will add this function to the `libNormaliz::Cone` or change the behaviour of the HilbertSeries?
