### ISSUE TITLE
integer hull

### ISSUE THREAD

**Issue by RichardSieg** [sebasguts/PyNormaliz#13]
when doing:
int_hull = rat_poly.IntegerHull()
print(int_hull.VerticesOfPolyhedron())

I currently have: 
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-12-48bb031fba56> in <module>()
      1 int_hull = rat_poly.IntegerHull()
----> 2 print(int_hull.VerticesOfPolyhedron())
      3 print(int_hull.SupportHyperplanes())

AttributeError: 'PyCapsule' object has no attribute 'VerticesOfPolyhedron'

**Comment by sebasguts** [comment]
That is actually a regression I introduced when remodelling the getters. I will take care of it. This is the only getter that will output a cone?

**Comment by RichardSieg** [comment]
Yes. Thank you!
