### ISSUE TITLE
License info missing

### ISSUE THREAD

**Issue by mkoeppe** [sebasguts/PyNormaliz#2]

**Comment by sebasguts** [comment]
Which Licence would you like to see, i.e., which makes it the easiest to include this in Sage? GPL2?

**Comment by mkoeppe** [comment]
Best would be "GPL2 or later" such as by using the following copyright notice

====
Copyright (C) yyyy  name of author

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
====

**Comment by sebasguts** [comment]
Thank you for your help
