### ISSUE TITLE
i686 build fails

### ISSUE THREAD

**Issue by antonio-rojas** [sebasguts/PyNormaliz#4]
Building 1.0 on i686 fails with:

NormalizModule.cpp: In function 'PyObject* NmzToPyLong(size_t)':
NormalizModule.cpp:120:11: error: redefinition of 'PyObject* NmzToPyLong(size_t)'
 PyObject* NmzToPyLong( size_t in ){
           ^~~~~~~~~~~
NormalizModule.cpp:114:11: note: 'PyObject* NmzToPyLong(libnormaliz::key_t)' previously defined here
 PyObject* NmzToPyLong( libnormaliz::key_t in ){
           ^~~~~~~~~~~
error: command 'gcc' failed with exit status 1

**Comment by sebasguts** [comment]
Hope this works. I do not have a 32-bit environment to test it, but I am pretty certain.

**Comment by sebasguts** [comment]
Please leave a positive or negative comment :)

**Comment by antonio-rojas** [comment]
Works now, thanks
